# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuOutput.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuOutput(object):
    def setupUi(self, MenuOutput):
        MenuOutput.setObjectName("MenuOutput")
        MenuOutput.resize(673, 435)
        self.centralwidget = QtWidgets.QWidget(MenuOutput)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle2 = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle2.setGeometry(QtCore.QRect(170, 10, 363, 38))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelTitle2.setFont(font)
        self.labelTitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle2.setObjectName("labelTitle2")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(20, 70, 331, 321))
        self.MplWidget.setObjectName("MplWidget")
        self.frameNilaiSoma = QtWidgets.QFrame(self.centralwidget)
        self.frameNilaiSoma.setGeometry(QtCore.QRect(380, 90, 271, 211))
        self.frameNilaiSoma.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameNilaiSoma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNilaiSoma.setObjectName("frameNilaiSoma")
        self.gridLayout = QtWidgets.QGridLayout(self.frameNilaiSoma)
        self.gridLayout.setObjectName("gridLayout")
        self.labelMesoResult = QtWidgets.QLabel(self.frameNilaiSoma)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.labelMesoResult.setFont(font)
        self.labelMesoResult.setObjectName("labelMesoResult")
        self.gridLayout.addWidget(self.labelMesoResult, 3, 1, 1, 1)
        self.labelMesomorph = QtWidgets.QLabel(self.frameNilaiSoma)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.labelMesomorph.setFont(font)
        self.labelMesomorph.setObjectName("labelMesomorph")
        self.gridLayout.addWidget(self.labelMesomorph, 3, 0, 1, 1)
        self.labelEctoResult = QtWidgets.QLabel(self.frameNilaiSoma)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.labelEctoResult.setFont(font)
        self.labelEctoResult.setObjectName("labelEctoResult")
        self.gridLayout.addWidget(self.labelEctoResult, 4, 1, 1, 1)
        self.labelType = QtWidgets.QLabel(self.frameNilaiSoma)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.labelType.setFont(font)
        self.labelType.setObjectName("labelType")
        self.gridLayout.addWidget(self.labelType, 5, 0, 1, 1)
        self.labelEndoResult = QtWidgets.QLabel(self.frameNilaiSoma)
        self.labelEndoResult.setMinimumSize(QtCore.QSize(148, 0))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.labelEndoResult.setFont(font)
        self.labelEndoResult.setObjectName("labelEndoResult")
        self.gridLayout.addWidget(self.labelEndoResult, 2, 1, 1, 1)
        self.labelSubtitle2 = QtWidgets.QLabel(self.frameNilaiSoma)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSubtitle2.setFont(font)
        self.labelSubtitle2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSubtitle2.setObjectName("labelSubtitle2")
        self.gridLayout.addWidget(self.labelSubtitle2, 1, 0, 1, 2)
        self.labelEctomorph = QtWidgets.QLabel(self.frameNilaiSoma)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.labelEctomorph.setFont(font)
        self.labelEctomorph.setObjectName("labelEctomorph")
        self.gridLayout.addWidget(self.labelEctomorph, 4, 0, 1, 1)
        self.labelEndomorph = QtWidgets.QLabel(self.frameNilaiSoma)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.labelEndomorph.setFont(font)
        self.labelEndomorph.setObjectName("labelEndomorph")
        self.gridLayout.addWidget(self.labelEndomorph, 2, 0, 1, 1)
        self.labelTypeResult = QtWidgets.QLabel(self.frameNilaiSoma)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.labelTypeResult.setFont(font)
        self.labelTypeResult.setObjectName("labelTypeResult")
        self.gridLayout.addWidget(self.labelTypeResult, 5, 1, 1, 1)
        self.buttonBack = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBack.setGeometry(QtCore.QRect(380, 320, 271, 41))
        self.buttonBack.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.buttonBack.setFont(font)
        self.buttonBack.setObjectName("buttonBack")
        MenuOutput.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuOutput)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 21))
        self.menubar.setObjectName("menubar")
        MenuOutput.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuOutput)
        self.statusbar.setObjectName("statusbar")
        MenuOutput.setStatusBar(self.statusbar)

        self.retranslateUi(MenuOutput)
        QtCore.QMetaObject.connectSlotsByName(MenuOutput)

    def retranslateUi(self, MenuOutput):
        _translate = QtCore.QCoreApplication.translate
        MenuOutput.setWindowTitle(_translate("MenuOutput", "MainWindow"))
        self.labelTitle2.setText(_translate("MenuOutput", "Somatotype Result"))
        self.labelMesoResult.setText(_translate("MenuOutput", ":"))
        self.labelMesomorph.setText(_translate("MenuOutput", "Mesomorph"))
        self.labelEctoResult.setText(_translate("MenuOutput", ":"))
        self.labelType.setText(_translate("MenuOutput", "Type"))
        self.labelEndoResult.setText(_translate("MenuOutput", ":"))
        self.labelSubtitle2.setText(_translate("MenuOutput", "Somatotype Score"))
        self.labelEctomorph.setText(_translate("MenuOutput", "Ectomorph"))
        self.labelEndomorph.setText(_translate("MenuOutput", "Endomorph"))
        self.labelTypeResult.setText(_translate("MenuOutput", ":"))
        self.buttonBack.setText(_translate("MenuOutput", "Back"))
from mplwidget import MplWidget
